export const menu = [
	{
		name: 'Pizza Slices',
		price: 100,
		review: 3,
		description: `Pizza slices are triangular or wedge-shaped portions of a round pizza, carefully cut to serve as individual servings. Each slice features a crispy or chewy crust that forms its outer edge, providing a satisfying crunch or softness. The base is a layer of dough, topped with a rich tomato sauce, which gives it a tangy foundation. A generous layer of melted cheese blankets the slice, offering gooey texture and flavor. Toppings like pepperoni, mushrooms, olives, or vegetables add variety and personalization to each piece. The aroma of freshly baked pizza slices is irresistible, mingling the scents of herbs, cheese, and spices. They are easy to hold, making them a perfect handheld meal or snack. Pizza slices are versatile, fitting for casual gatherings, parties, or a quick bite. Whether served piping hot or cold, they deliver a satisfying burst of flavor in every bite.`,
		imageUrl: 'menu-1.jpg',
		id: 1,
	},
	{
		name: 'Cake Salad',
		price: 350,
		review: 4,
		description: `Cake salad is a heavenly fusion of soft, moist cake cubes and fresh, juicy fruits, all enveloped in a luscious, creamy dressing. Imagine biting into a burst of sweetness as fluffy vanilla or chocolate cake mingles with the tang of strawberries, the succulence of mangoes, or the refreshing crunch of apples. A silky drizzle of whipped cream or yogurt, lightly sweetened and perfectly chilled, ties it all together. For an extra layer of indulgence, a sprinkle of crushed nuts or shredded coconut adds a delightful crunch. The symphony of flavors and textures dances on your taste buds, leaving you craving more. Whether served in elegant layers or tossed together in a bowl, cake salad is a dessert dream come true. One spoonful, and you’re hooked on its luxurious, melt-in-your-mouth decadence.`,
		imageUrl: 'menu-2.jpg',
		id: 2,
	},
	{
		name: 'Cheese and Charcuterie Board',
		price: 400,
		review: 4,
		description: `A showcases of a mouthwatering Cheese and Charcuterie Board, a feast for the eyes and the palate. The centerpiece is a rustic wooden board laden with an array of delectable treats. A small pot of melted cheese, bubbling with golden goodness, sits alongside slices of crisp apples and juicy grapes. A medley of crackers and small sausages completes the picture. The aroma of melted cheese, the tangy sweetness of the grapes, and the savory crunch of the crackers combine to create a symphony of flavors that will tantalize your taste buds. It's the perfect accompaniment to a glass of wine or a cold beer, making it the ideal choice for a casual get-together or a special occasion.`,
		imageUrl: 'menu-3.jpg',
		id: 3,
	},
	{
		name: 'Rainbow Smoothie Bowl',
		price: 75,
		review: 5,
		description: `A vibrant and refreshing Rainbow Smoothie Bowl, a feast for the eyes and a nutritional powerhouse. The bowl is filled with a vibrant green smoothie base, topped with a colorful array of fruits and seeds. Slices of strawberries, blueberries, and orange segments add a burst of sweetness and antioxidants. Edible flowers and a sprinkle of chia seeds provide a touch of elegance and additional nutrients. The smoothie is garnished with a sprig of mint, adding a touch of freshness and aroma. This smoothie bowl is not only visually stunning but also packed with vitamins, minerals, and antioxidants, making it a delicious and healthy way to start your day.`,
		imageUrl: 'menu-4.jpg',
		id: 4,
	},
	{
		name: 'A Vibrant Fruit Salad',
		price: 200,
		review: 5,
		description: `The vibrant green of the pesto sauce coats the plump, bow-shaped pasta, each one a masterpiece of al dente perfection. The sauce itself, a fragrant blend of fresh basil, pine nuts, Parmesan cheese, and garlic, clings to every curve, promising a burst of flavor with each bite. Scattered across the dish, like rubies amidst emeralds, are plump, juicy cherry tomatoes, their bright red hue contrasting beautifully with the verdant pesto. The tomatoes, still warm from the pan, burst with sweet, tangy juices that mingle with the rich, savory sauce. A bed of crisp, fresh greens provides a refreshing counterpoint to the richness of the pasta and sauce. Each forkful is a symphony of textures and flavors, the smooth, creamy pesto, the al dente pasta, the burst of juicy tomatoes, and the crisp greens working together in perfect harmony. The aroma of basil and garlic fills the air, inviting you to indulge in this culinary delight. It's a dish that celebrates the simplicity of fresh ingredients and the magic of Italian cuisine.`,
		imageUrl: 'menu-5.jpg',
		id: 5,
	},
	{
		name: 'Strawberry Sundae',
		price: 150,
		review: 4,
		description: `A pristine white bowl filled to the brim with a creamy, vanilla ice cream. Nestled within the icy goodness are plump, ripe strawberries, their vibrant red hue contrasting beautifully with the cool, white backdrop. A drizzle of sweet strawberry sauce cascades down the sides of the bowl, creating a mesmerizing interplay of colors and textures. The aroma of vanilla and ripe strawberries fills the air, promising a taste sensation that will transport you to a blissful state. The ice cream itself is a dream, smooth and velvety, with a subtle sweetness that perfectly complements the tartness of the strawberries. Each spoonful is a symphony of flavors and textures, a delightful indulgence that will leave you craving for more.`,
		imageUrl: 'menu-6.jpg',
		id: 6,
	},
	{
		name: 'Raspberry Tart',
		price: 70,
		review: 3,
		description: `A miniature masterpiece of pastry and fruit, this raspberry tart is a sight to behold. The golden-brown crust, flaky and buttery, cradles a generous filling of sweet raspberry compote. Atop the compote, a crown of plump, juicy raspberries, their vibrant red hue contrasting beautifully with the golden crust. A drizzle of dark chocolate adds a touch of richness and elegance, completing this decadent dessert. The aroma of sweet berries and buttery pastry is simply irresistible, promising a taste sensation that will delight the senses.`,
		imageUrl: 'menu-7.jpg',
		id: 7,
	},
	{
		name: 'Sweet and Sour Chicken',
		price: 320,
		review: 5,
		description: `A vibrant tapestry of flavors and textures unfolds on the plate. Golden-brown pieces of crispy chicken, each bite a perfect balance of crunchy exterior and tender interior, are bathed in a luscious, sweet and sour sauce. The sauce itself is a symphony of flavors, a harmonious blend of tangy pineapple, sweet bell peppers, and savory onions, all simmered to perfection in a rich, caramelized glaze. The aroma is intoxicating, a tantalizing blend of sweet, sour, and savory that promises a culinary adventure. Each spoonful is a delightful surprise, the crispy chicken contrasting beautifully with the soft, juicy vegetables and the tangy sauce, creating a symphony of textures and tastes that will leave you craving for more.`,
		imageUrl: 'menu-8.jpg',
		id: 8,
	},
	{
		name: 'Sweet and Sour Tofu',
		price: 180,
		review: 4,
		description: `A vibrant symphony of flavors and textures awaits on this plate. Golden-brown cubes of tofu, crispy on the outside and soft on the inside, are bathed in a luscious, sweet and sour sauce. The sauce, a harmonious blend of tangy pineapple, sweet bell peppers, and savory onions, is simmered to perfection, creating a rich, caramelized glaze that clings to every bite. A bed of fluffy white rice provides the perfect canvas for this culinary masterpiece, absorbing the sweet and sour flavors and adding a comforting touch. The aroma is intoxicating, a tantalizing blend of sweet, sour, and savory that fills the air, promising a taste sensation that will delight the senses. Each bite is a journey through a world of flavor, the crispy tofu contrasting beautifully with the soft, juicy vegetables and the tangy sauce, creating a symphony of textures and tastes that will leave you craving for more.`,
		imageUrl: 'menu-9.jpg',
		id: 9,
	},
	{
		name: 'Hearty Sesame Seed Sandwich',
		price: 100,
		review: 4,
		description: `A hearty sandwich, held aloft by a hand adorned with vibrant purple nails, promises a satisfying bite. The bread, speckled with seeds, boasts a golden-brown crust, hinting at a perfectly toasted interior. A generous filling spills out from the sides, a tantalizing mix of juicy meats, crisp vegetables, and melted cheese. The aroma of toasted bread, savory meats, and tangy sauces fills the air, inviting you to take a bite. Each mouthful is a symphony of flavors and textures, the soft bread contrasting beautifully with the crisp vegetables and the tender meat. A true feast for the senses, this sandwich is sure to satisfy any hunger.`,
		imageUrl: 'menu-10.jpg',
		id: 10,
	},
	{
		name: 'Rainbow Sprinkle Donut Stack',
		price: 150,
		review: 5,
		description: `A tower of indulgence, a trio of delectable donuts, awaits. The topmost donut, a masterpiece of colorful sprinkles, dances with a riot of hues, inviting a playful bite. Beneath it, a classic chocolate glazed donut, its rich, dark coating glistening under the light, promises a decadent treat. The base of the tower, another chocolate glazed donut, is adorned with a whimsical drizzle of white chocolate, adding a touch of elegance to the ensemble. The sweet aroma of glazed donuts fills the air, promising a delightful sensory experience. Each bite is a burst of flavor, the soft, fluffy dough contrasting perfectly with the sweet, indulgent glaze. A true indulgence for the senses, this tower of donuts is sure to satisfy any sweet tooth.`,
		imageUrl: 'menu-11.jpg',
		id: 11,
	},
	{
		name: 'Crispy Pork Cutlets with Creamy Mashed Potatoes',
		price: 220,
		review: 5,
		description: `A feast for the eyes and the palate, this dish is a symphony of textures and flavors. Two golden-brown, crispy pork cutlets, their surfaces glistening with sea salt and adorned with fresh green onions, rest atop a mound of creamy mashed potatoes. The cutlets, with their perfectly crisp exterior and tender, juicy interior, promise a delightful contrast to the smooth, buttery potatoes. The aroma of roasted pork and buttery potatoes fills the air, inviting you to indulge in this culinary masterpiece. Each bite is a journey through a world of flavor. The crispy exterior of the cutlet gives way to a tender, juicy interior, while the creamy mashed potatoes provide a comforting contrast. The saltiness of the pork is balanced by the sweetness of the potatoes, creating a harmonious blend of flavors. The fresh green onions add a bright, herbaceous note, elevating the dish to new heights. This dish is a celebration of simple, wholesome ingredients, prepared with care and precision. It is a dish that nourishes the body and soul, a true feast for the senses.`,
		imageUrl: 'menu-12.jpg',
		id: 12,
	},
];
